config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "homes/index"
  root to: "homes#index"
  
  devise_for :users
  
 resources :projects do
  resources :bugs do
    member do
      patch :assign_to_self, :update_status # This creates the route for the action
    end
  end
end

end

app/models/project.rb
class Project < ApplicationRecord
 belongs_to :user
  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users
  has_many :bugs, dependent: :destroy 

  validates :name, presence: true, uniqueness: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 500 }
 def self.ransackable_attributes(auth_object = nil)
    %w[id name description created_at updated_at user_id]
 end

 def developers
    users.where(user_type: 'developer')
 end

  def qas
    users.where(user_type: 'qa')
  end
  accepts_nested_attributes_for :users
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  def index
    if current_user.developer?
     if params[:query].present?
       @projects = current_user.projects.where('name LIKE ?', "%#{params[:query]}%")
     else
       @projects = current_user.projects
     end
    else
     if params[:query].present?
       @projects = Project.where('name LIKE ?', "%#{params[:query]}%")
     else
       @projects = Project.all
     end
    end
  end

  def new
    @project = Project.new
    @users = User.where(user_type: ['developer', 'qa']) 
  end

  def show
    @project = Project.find(params[:id])
    @bugs = @project.bugs  
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id 

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      @users = User.where(user_type: ['developer', 'qa'])  
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    @users = User.where(user_type: ['developer', 'qa'])  
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      @users = User.where(user_type: ['developer', 'qa']) 
      render :edit
    end
  end

def destroy
    @project = Project.find(params[:id])
    authorize! :destroy, @project
    @project.destroy
    redirect_to projects_path, notice: 'Project deleted successfully!'
  end
  private

  def project_params
    params.require(:project).permit(:name, :description, user_ids: [])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h1 class="mb-4">Edit Project</h1>

<%= form_with(model: @project, local: true, class: "mb-4") do |form| %>
  <% if @project.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control", rows: 3 %>
  </div>

  <h3>Assign Users:</h3>
  <div class="mb-3">
    <%= form.collection_check_boxes :user_ids, @users, :id, :display_name_with_type do |b| %>
      <div class="form-check">
        <%= b.check_box(class: "form-check-input") %>
        <%= b.label(class: "form-check-label") %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.submit "Update Project", class: "btn btn-primary" %>
  </div>
<% end %>

<div class="mt-3">
          <%= link_to 'Back', project_path(@project), class: 'btn btn-info' %>
</div>

app/views/projects/index.html.erb
<h1 align="center">Projects</h1> <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-danger", style: "float: right"; %>

<div>
  <%= form_with url: projects_path, method: :get, local: true, id: 'project-search-form' do %>
    <%= text_field_tag :query, params[:query], placeholder: "Search for a project", style: "width: 300px;
  padding: 8px;
  margin-bottom: 20px;"%>
    <%= submit_tag 'Search', style: "display:solid;" %> <!-- Hide the button, optional -->
  <% end %>
</div>

<% if current_user.manager? %>
  <%= link_to 'New Project', new_project_path, class: "btn btn-primary mb-3" %>
<% end %>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td>
          <%= link_to 'Show', project_path(project), class: 'btn btn-info btn-sm' %>
            <% if can? :update, project %>
        <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-warning btn-sm' %>
        <% end %>
            <% if can? :destroy, project %>
        <%= button_to 'Delete', project_path(project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'; %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1 class="mb-4">New Project</h1>

<%= form_with(model: @project, local: true, class: "mb-4") do |form| %>
  <% if @project.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control", rows: 3 %>
  </div>

  <h3>Assign Users:</h3>
  <div class="mb-3">
    <%= form.collection_check_boxes :user_ids, @users, :id, :display_name_with_type do |b| %>
      <div class="form-check">
        <%= b.check_box(class: "form-check-input") %>
        <%= b.label(class: "form-check-label") %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.submit "Create Project", class: "btn btn-primary" %>
  </div>
<% end %>

<div class="mt-3">
  <%= link_to 'Back to Projects', projects_path, class: "btn btn-success" %>
</div>

app/views/projects/show.html.erb
<h1 class="mb-4"  style="text-align: center;">Project Name: <%= @project.name %></h1> 
<%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-danger", style: "float: right"; %> <h2 style="float: right;">|</h2> <%= link_to 'Projects Portal', projects_path, class: "btn btn-primary mb-2", style: "float: right" ;%>


<p class="lead"><strong>Description:</strong> <%= @project.description %></p>

<h2 class="mt-4">Assigned Users:</h2>
<ul class="list-group mb-4">
  <% @project.users.each do |user| %>
    <li class="list-group-item">
      <%= user.name %> (<%= user.user_type.humanize %>)
    </li>
  <% end %>
</ul>



<div class="mt-3">
        <% if can? :update, @project %>
        <%= link_to 'Update Project', edit_project_path(@project), class: 'btn btn-warning' %>
        <% end %>
</div>
<br>
<div class="mt-3">
        <% if can? :destroy, @project %>
        <%= button_to 'Delete Project', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'; %>
        <% end %>
      </div>

    <div class="mt-4">
    <h3 style="float: left;">Bugs Associated with this Project</h3>
<% if can? :create, Bug %>
 <%= link_to 'Manage Bugs And Features', project_bugs_path(@project),class: 'btn btn-warning', style: "float: right" %>
    <% end %>


   <% if can? :create, Bug %>
  <%= link_to "Report a New Bug", new_project_bug_path(@project), class: 'btn btn-secondary',style: "float: right";%>
<% end %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Category</th>
          <th scope="col">Status</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @project.bugs.each do |bug| %>
          <tr>
            <td><%= bug.title %></td>
            <td><%= bug.category.humanize %></td>
            <td><%= bug.status.humanize %></td>
            <td>
              <%= link_to 'View', project_bug_path(@project, bug), class: 'btn btn-info btn-sm' %>
             
              <% if can? :destroy, @bug %>

              <%= button_to 'Delete', project_bug_path(@project, bug), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>