config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "homes/index"
  root to: "homes#index"
  
  devise_for :users
  
 resources :projects do
  resources :bugs do
    member do
      patch :assign_to_self, :update_status # This creates the route for the action
    end
  end
end

end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :project
  belongs_to :user 
  belongs_to :developer, class_name: 'User', optional: true 

  mount_uploader :screenshot, ScreenshotUploader 

  
  enum category: { bug: 0, feature: 1 }
  enum status: { not_started: 0, started: 1, resolved: 2, completed: 3 }


  
  validates :title, presence: true, uniqueness: { scope: :project_id, message: "Bug with this title already exists" }

  validates :category, :status, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :deadline, presence: true
  validates :screenshot, format: { with: /\.(png|gif)\z/i, message: "Only .png or .gif formats are allowed" }, allow_blank: true

  validate :deadline_cannot_be_in_the_past
  private
 
  def deadline_cannot_be_in_the_past
    if deadline.present? && deadline < Time.current
      errors.add(:deadline, "can't be in the past")
    end
  end

  def screenshot_format
    if screenshot.present? && !screenshot.file.content_type.in?(%w[image/png image/gif])
      errors.add(:screenshot, "must be a GIF or PNG image")
    end
  end
    def self.ransackable_attributes(auth_object = nil)
    ["category", "created_at", "deadline", "description", "developer_id", "id", "project_id", "screenshot", "status", "title", "updated_at", "user_id"]
    end
  
  def self.ransackable_associations(auth_object = nil)
    ["developer", "project", "user"]
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_project
  before_action :find_bug, only: [:show, :edit, :update, :destroy, :assign_to_self]
  before_action :set_bug, only: [:show, :update_status]
    
  def update_status
  if @bug.update_column(:status, params[:bug][:status])
    redirect_to project_bug_path(@project, @bug), notice: "Bug status updated successfully."
  else
    redirect_to project_bug_path(@project, @bug), alert: "Failed to update status."
  end
end

def assign_to_self
  if @bug.developer_id && @bug.developer_id != current_user.id
    # Reassigning the bug to the current user
    if @bug.update_column(:developer_id, current_user.id)
      redirect_to project_bug_path(@project, @bug), notice: "Bug successfully reassigned to you."
    else
      redirect_to project_bug_path(@project, @bug), alert: "Failed to reassign bug."
    end
  elsif @bug.developer_id.nil?
    # Assigning the bug to the current user for the first time
    if @bug.update_column(:developer_id, current_user.id)
      redirect_to project_bug_path(@project, @bug), notice: "Bug assigned to you successfully."
    else
      redirect_to project_bug_path(@project, @bug), alert: "Failed to assign bug."
    end
  else
    redirect_to project_bug_path(@project, @bug), alert: "You are already assigned to this bug."
  end
end

  def index
    @bugs = @project.bugs
  end

   def show
      @project = Project.find(params[:project_id])
      @bug = @project.bugs.find(params[:id])
   end

  def new
    @bug = @project.bugs.new
   @developers = User.where(user_type: 'developer') 
  end

  def create

    @bug = @project.bugs.new(bug_params)
    @developers = User.where(user_type: 'developer')
    @bug.user = current_user 
    if @bug.save
      redirect_to project_bugs_path(@project, @bug), notice: 'Bug reported successfully.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @developers = User.where(user_type: 'developer')
  end

  def update
    @developers = User.where(user_type: 'developer')

    if @bug.update(bug_params)
      redirect_to project_bug_path(@bug.project, @bug), notice: 'Bug updated successfully.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bug.destroy
    redirect_to project_bugs_path(@project), notice: 'Bug deleted successfully.'
  end

  private

  def set_bug
    @bug = Bug.find(params[:id])
  end

  def bug_status_params
    params.require(:bug).permit(:status) # Only permit status change
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def find_bug
    @bug = @project.bugs.find(params[:id])
  end

  def bug_params
    params.require(:bug).permit(:title, :description, :category, :status, :developer_id, :deadline, :screenshot)
  end
end

app/helpers/bugs_helper.rb
module BugsHelper
  def human_readable_status(bug)
    case bug.status
    when "not_started"
      "New"
    when "started"
      "Started"
    when "completed"
      "Completed"
    when "resolved"
      "Resolved"
    else
      "Unknown"
    end
  end
end

app/views/bugs/_form.html.erb
<%= form_with(model: [@project, @bug], local: true) do |form| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% @bug.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  
  <div class="form-group">
    <%= form.label :category, "Category" %>
    <%= form.select :category, Bug.categories.keys.map { |key| [key.humanize, key] }, { prompt: "Select Category" }, { class: "form-control", id: 'category_select' } %>
  </div>

  
  <div class="form-group">
    <%= form.label :status, "Status" %>
    <%= form.select :status, [], {}, { class: "form-control", id: 'status_select', 'data-current-status': @bug.status } %>
  </div>

  
  <div class="form-group">
    <%= form.label :developer_id, "Assign Developer" %>
    <%= form.collection_select :developer_id, @developers, :id, :name, { prompt: "Select Developer" }, { class: "form-control" } %>
  </div>

  
  <div class="form-group">
    <%= form.label :deadline %>
    <%= form.datetime_select :deadline, class: "form-control" %>
  </div>

  
  <div class="form-group">
    <%= form.label :screenshot %>
    <%= form.file_field :screenshot, class: "form-control-file" %>
  </div>

  
  <div>
    <%= form.submit "Submit Bug", class: "btn btn-primary" %>
  </div>


<% end %>

app/views/bugs/edit.html.erb
<h1>Edit Bug</h1> 

<%= render 'form', project: @project, bug: @bug %>

<%= link_to 'Back to Bug', project_bug_path(@project, @bug) %>

app/views/bugs/index.html.erb
<h1 class="text-center mb-4">Bugs for <%= @project.name %></h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Type</th>
      <th scope="col">Status</th>
      <th scope="col">Developer</th>
      <th scope="col" class="text-center">Edit</th>
      <th scope="col" class="text-center">Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <tr>
        <td><%= link_to bug.title, project_bug_path(@project, bug), class: "text-decoration-none" %></td>
        <td><%= bug.category.humanize %></td>
        <td><%= bug.status.humanize %></td>
        <td><%= bug.developer&.name || 'Unassigned' %></td>
        <td class="text-center">
          <% if can?(:edit, bug) %>
            <%= link_to 'Edit', edit_project_bug_path(@project, bug), class: "btn btn-warning btn-sm" %>
          <% end %>
        </td>
        <td class="text-center">
          <% if can?(:destroy, bug) %>
            <%= link_to 'Delete', project_bug_path(@project, bug), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-right">
  <%= link_to 'New Bug', new_project_bug_path(@project), class: "btn btn-success" %>
  <%= link_to 'Back to Project', project_path(@project), class: 'btn btn-info' %>

</div>

app/views/bugs/new.html.erb
<h1>Report a New Bug</h1>

<%= render 'form', project: @project, bug: @bug %>
<br>
<div>
<%= link_to 'Bugs List', project_bugs_path(@project),class: 'btn btn-warning' %>
</div>
<br>
 <div>
    <%= link_to 'Projects Portal', projects_path, class: "btn btn-primary mb-2" %>

  </div>

app/views/bugs/show.html.erb
<div><h1>Bug Details</h1> <br>
  </div>

<div class="card mb-4">
  <div class="card-body">
    <p><strong>Title:</strong> <%= @bug.title %></p>
    <p><strong>Description:</strong> <%= @bug.description %></p>
    <p><strong>Project:</strong> <%= @bug.project.name %></p>
    <p><strong>Category:</strong> <%= @bug.category.humanize %></p>
    <p><strong>Status:</strong> <%= @bug.status.humanize %></p>
    <p><strong>Assigned Developer:</strong> <%= @bug.developer ? @bug.developer.name : 'Unassigned' %></p>
    <p><strong>Deadline:</strong> <%= @bug.deadline.present? ? @bug.deadline.strftime("%B %d, %Y %H:%M") : 'No deadline set' %></p>

    <p><strong>Screenshot:</strong>
      <% if @bug.screenshot.present? %>
        <%= image_tag @bug.screenshot.url, class: 'img-fluid' %>
      <% else %>
        No screenshot available.
      <% end %>
    </p>

    <% if current_user.user_type == 'developer' && @bug.developer_id != current_user.id %>
      <%= button_to "Assign to Me", assign_to_self_project_bug_path(@project, @bug), method: :patch, class: 'btn btn-primary' %>
    <% elsif current_user.user_type == 'developer' && @bug.developer_id == current_user.id %>
      <p class="text-success">You are currently assigned to this bug.</p>
    <% end %>

    <% if @bug.developer_id == current_user.id %>
      <%= form_with model: @bug, url: update_status_project_bug_path(@project, @bug), method: :patch, local: true do |f| %>
        <div class="form-group">
          <%= f.label :status, "Change Status" %>
          <%= f.select :status, Bug.statuses.keys, {}, class: 'form-control' %>
        </div>
        <%= f.submit "Update Status", class: 'btn btn-secondary' %>
      <% end %>
    <% end %>

    <% if can? :edit, @bug %>
        <%= link_to 'Edit Bug', edit_project_bug_path(@project, @bug), class: 'btn btn-warning' %>
        <% end %>

    <% if can?(:destroy, @bug) %>
  <%= button_to "Delete", project_bug_path(@project, @bug), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
<% end %>
    <div>
  <%= link_to 'Back to Project', project_path(@project), class: 'btn btn-info' %>

    </div>
  </div>

</div>